version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress_network

  # WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8081:80"
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      # If you want to mount your custom theme or plugins, uncomment these lines
      # - ./wp-content/themes/boostlab:/var/www/html/wp-content/themes/boostlab
      # - ./wp-content/plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        /* REST API settings */
        define('JWT_AUTH_SECRET_KEY', 'joh316');
        define('JWT_AUTH_CORS_ENABLE', true);
    networks:
      - wordpress_network

networks:
  wordpress_network:

volumes:
  db_data:
  wordpress_data: